In [1]:
import cv2
import numpy as np

In [3]:
image_path = '/Users/acemitto/Desktop/STUDY/ACE/CAPSTONE/vietnamese-traffic-system/Source/Traffic-Rule-Violation-Detection-System-master/Test_color/green.png'
img = cv2.imread(image_path)

In [25]:
# min and max HSV values
red_min = np.array([0,5,150])
red_max = np.array([8,255,255])
red_min2 = np.array([175,5,150])
red_max2 = np.array([180,255,255])

yellow_min = np.array([20,5,150])
yellow_max = np.array([30,255,255])

green_min = np.array([35,5,150])
green_max = np.array([90,255,255])


greenRGB = np.uint8([[[0,255,255]]])
greenHSV = cv2.cvtColor(greenRGB, cv2.COLOR_RGB2HSV) 
print(greenHSV)

[[[ 90 255 255]]]


In [26]:
greenRGB = np.uint8([[[0,255,255]]])
greenHSV = cv2.cvtColor(greenRGB, cv2.COLOR_RGB2HSV) 
print(greenHSV)

[[[ 90 255 255]]]


In [27]:
HSV = np.uint8([[[35,5,150]]])
RGB = cv2.cvtColor(HSV, cv2.COLOR_HSV2RGB) 
print(RGB)

[[[150 150 147]]]


In [14]:
 # convert BGR image to HSV
desired_dim = (90, 30)  # width, height
rlimg = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
rlimg = cv2.resize(np.array(rlimg), desired_dim, interpolation=cv2.INTER_LINEAR)
hsv_img = cv2.cvtColor(rlimg, cv2.COLOR_RGB2HSV)

# min and max HSV values
red_min = np.array([0,5,150])
red_max = np.array([8,255,255])
red_min2 = np.array([175,5,150])
red_max2 = np.array([180,255,255])

yellow_min = np.array([20,5,150])
yellow_max = np.array([30,255,255])

green_min = np.array([35,5,150])
green_max = np.array([90,255,255])

# apply red, yellow, green thresh to image
# 利用cv2.inRange函数设阈值，去除背景部分
red_thresh = cv2.inRange(hsv_img,red_min,red_max)+cv2.inRange(hsv_img,red_min2,red_max2)
yellow_thresh = cv2.inRange(hsv_img,yellow_min,yellow_max)
green_thresh = cv2.inRange(hsv_img,green_min,green_max)

# apply blur to fix noise in thresh
# 进行中值滤波
red_blur = cv2.medianBlur(red_thresh,5)
yellow_blur = cv2.medianBlur(yellow_thresh,5)
green_blur = cv2.medianBlur(green_thresh,5)

# checks which colour thresh has the most white pixels
red = cv2.countNonZero(red_blur)
yellow = cv2.countNonZero(yellow_blur)
green = cv2.countNonZero(green_blur)
print(hsv_img)
# the state of the light is the one with the greatest number of white pixels
lightColor = max(red,yellow,green)

[[[100  42 109]
  [ 98  36 113]
  [ 98  32 118]
  ...
  [ 97  43 132]
  [ 98  35 161]
  [ 10   8  93]]

 [[ 99  30 118]
  [ 96  31 115]
  [ 99  31 117]
  ...
  [101  40 154]
  [104  38 167]
  [ 10   8  93]]

 [[ 97  28 120]
  [ 95  26 116]
  [ 99  30 119]
  ...
  [101  38 163]
  [103  38 168]
  [ 10   8  93]]

 ...

 [[ 75   3 154]
  [ 45   3 153]
  [ 30   2 151]
  ...
  [101  56  73]
  [102  68  75]
  [ 15   5 100]]

 [[ 45   3 158]
  [ 30   3 156]
  [ 40   5 156]
  ...
  [102  45  73]
  [102  58  75]
  [ 20   8 100]]

 [[ 60   5  52]
  [  0   0  51]
  [ 30   5  51]
  ...
  [105  36  28]
  [102  44  29]
  [  0   0 103]]]


In [ ]:
int i;   
int o;  

o=(192-((i<<8)/360))&255;

i=((192-o)*360)>>8;